<?php
/**
 * @author    ThemePunch <info@themepunch.com>
 * @link      https://www.themepunch.com/
 * @copyright 2019 ThemePunch
 */

$rsaf	= new RevSliderFunctionsAdmin();
$rsa	= $rsaf->get_short_library();
$rsupd	= new RevSliderPluginUpdate();
$rsaddon= new RevSliderAddons();

$rs_addon_update		 = $rsaddon->check_addon_version();
$rs_addons				 = $rsaddon->get_addon_list();
$rs_wp_date_format		 = Mage::helper('nwdrevslider/framework')->get_option('date_format');
$rs_wp_time_format		 = Mage::helper('nwdrevslider/framework')->get_option('time_format');
$rs_added_image_sizes	 = $rsaf->get_all_image_sizes();
$rs_image_meta_todo		 = Mage::helper('nwdrevslider/framework')->get_option('rs_image_meta_todo', array());
$rs_slider_update_needed = $rsupd->slider_need_update_checks();
$rs_global_settings		 = $rsaf->get_global_settings();
$rs_global_sizes		 = array(
	'd' => $rsaf->get_val($rs_global_settings, array('size', 'desktop'), '1240'),
	'n' => $rsaf->get_val($rs_global_settings, array('size', 'notebook'), '1024'),
	't' => $rsaf->get_val($rs_global_settings, array('size', 'tablet'), '778'),
	'm' => $rsaf->get_val($rs_global_settings, array('size', 'mobile'), '480')
);
$rs_show_updated = Mage::helper('nwdrevslider/framework')->get_option('rs_cache_overlay', Nwdthemes_Revslider_Helper_Framework::RS_REVISION);
if(version_compare(Nwdthemes_Revslider_Helper_Framework::RS_REVISION, $rs_show_updated, '>')){
    Mage::helper('nwdrevslider/framework')->update_option('rs_cache_overlay', Nwdthemes_Revslider_Helper_Framework::RS_REVISION);
}
$rs_notices = $rsaf->add_notices();
$rs_color_picker_presets = RSColorpicker::get_color_presets();
?>
<!-- GLOBAL VARIABLES -->
<script type="text/javascript">

    var ajaxurl = '<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/ajax'); ?>?isAjax=true',
		revMageImageUploadUrl = '<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/nwdimages/index/type/[type]'); ?>',
		overviewUrl = '<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider'); ?>',
		wpColorPickerL10n = <?php echo json_encode(array(
			'clear' => $this->__('Clear'),
			'defaultString' => $this->__('Default'),
			'pick' => $this->__('Select Color'),
			'current' => $this->__('Current Color')
		)); ?>;

    (function(jQuery) {

	window.RVS = window.RVS === undefined ? {F:{}, C:{}, ENV:{}, LIB:{}, V:{}, S:{}, DOC:jQuery(document), WIN:jQuery(window)} : window.RVS;

	RVS.LIB.ADDONS = RVS.LIB.ADDONS === undefined ? {} : RVS.LIB.ADDONS;
	RVS.LIB.ADDONS			= jQuery.extend(true,RVS.LIB.ADDONS,<?php echo (!empty($rs_addons)) ? 'jQuery.parseJSON('.$rsaf->json_encode_client_side($rs_addons).')' : '{}'; ?>);
	RVS.LIB.OBJ 			= {types: jQuery.parseJSON(<?php echo $rsaf->json_encode_client_side($rsa); ?>)};
	RVS.LIB.SLIDERS			= <?php echo json_encode(RevSliderSlider::get_sliders_short_list()); ?>;
	RVS.LIB.COLOR_PRESETS	= <?php echo (!empty($rs_color_picker_presets)) ? 'jQuery.parseJSON('. $rsaf->json_encode_client_side($rs_color_picker_presets) .')' : '{}'; ?>;

	RVS.ENV.addOns_to_update = <?php echo (!empty($rs_addon_update)) ? 'jQuery.parseJSON('.$rsaf->json_encode_client_side($rs_addon_update).');' : '{};'; ?>
	RVS.ENV.activated		= '<?php echo (Mage::helper('nwdrevslider/framework')->get_option('revslider-valid', 'false')) == 'true' ? 'true' : 'false'; ?>';
	RVS.ENV.activated = RVS.ENV.activated=='true'  || RVS.ENV.activated==true ? true : false;
	RVS.ENV.nonce			= '<?php echo Mage::helper('nwdrevslider/framework')->wp_create_nonce('revslider_actions'); ?>';
	RVS.ENV.plugin_dir		= 'revslider';
	RVS.ENV.slug_path		= '<?php echo Nwdthemes_Revslider_Helper_Framework::RS_PLUGIN_SLUG_PATH; ?>';
	RVS.ENV.slug			= '<?php echo Nwdthemes_Revslider_Helper_Framework::$RS_PLUGIN_SLUG; ?>';
	RVS.ENV.plugin_url		= '<?php echo Nwdthemes_Revslider_Helper_Framework::$RS_PLUGIN_URL; ?>';
	RVS.ENV.wp_plugin_url 	= '<?php echo Nwdthemes_Revslider_Helper_Framework::$WP_PLUGIN_URL . "/"; ?>';
	RVS.ENV.admin_url		= '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/nwdrevslider/slide'); ?>';
	RVS.ENV.revision		= '<?php echo Nwdthemes_Revslider_Helper_Framework::RS_REVISION; ?>';
	RVS.ENV.updated			= <?php echo (version_compare(Nwdthemes_Revslider_Helper_Framework::RS_REVISION, $rs_show_updated, '>')) ? 'true' : 'false'; ?>;
	RVS.ENV.latest_version	= '<?php echo Mage::helper('nwdrevslider/framework')->get_option('revslider-latest-version', Nwdthemes_Revslider_Helper_Framework::RS_REVISION); ?>';
	RVS.ENV.placeholder		= {
		date_format: '<?php echo $rs_wp_date_format; ?>',
		time_format: '<?php echo $rs_wp_time_format; ?>',
		date_today:	 '<?php echo date($rs_wp_date_format); ?>',
		time:		 '<?php echo date($rs_wp_time_format); ?>',
		tomorrow:	 '<?php echo date($rs_wp_date_format, strtotime(date($rs_wp_date_format) . ' +1 day')); ?>',
		last_week:	 '<?php echo date($rs_wp_date_format, strtotime(date($rs_wp_date_format) . ' -7 day')); ?>',
		date:				'<?php echo date($rs_wp_date_format); ?>',
		date_modified:		'<?php echo date($rs_wp_date_format); ?>'
	};
	RVS.ENV.glb_slizes		= jQuery.parseJSON(<?php echo $rsaf->json_encode_client_side($rs_global_sizes); ?>);
	RVS.ENV.img_sizes		= jQuery.parseJSON(<?php echo $rsaf->json_encode_client_side($rs_added_image_sizes); ?>);
	RVS.ENV.create_img_meta	= <?php echo (!empty($rs_image_meta_todo)) ? 'true' : 'false'; ?>;
	RVS.ENV.notices			= <?php echo (!empty($rs_notices)) ? 'jQuery.parseJSON('. $rsaf->json_encode_client_side($rs_notices) .')' : '[]'; ?>;
	<?php
	if($rs_slider_update_needed == true){
	?>
	var RS_DO_SILENT_SLIDER_UPDATE = <?php echo ($rs_slider_update_needed == true) ? 'true' : 'false'; ?>;

	if(RS_DO_SILENT_SLIDER_UPDATE === true){
		//push request to update slider for slider until finished
		jQuery(document).ready(function(){
			rs_do_silent_update();
		});
	}

	function rs_do_silent_update(){
		RVS.F.ajaxRequest('silent_slider_update', {}, function(response){
			if(response.status !== 'finished'){
				rs_do_silent_update();
			}else{
				RS_DO_SILENT_SLIDER_UPDATE = false;
			}
		}, true);
	}
	<?php
	}
	?>
    })($nwd_jQuery);
</script>
<?php
Mage::helper('nwdrevslider/framework')->do_action('revslider_header_content', $rsaf);
?>

<?php
//added for builder
?>
<script src="https://player.vimeo.com/api/player.js"></script>
<script src="https://www.youtube.com/iframe_api"></script>
<!-- COLLECTOR FOR ADDONS -->

<div id="wpbody">

<!-- WAIT A MINUTE OVERLAY CONTAINER -->
<div id="waitaminute">
	<div class="waitaminute-message"><i class="eg-icon-emo-coffee"></i><br><?php echo $this->__('Please Wait...', 'revslider'); ?></div>
</div>

<!-- TOP RIGHT CORNER INFORMATION CONTAINER -->
<div id="rb_maininfo_wrap"></div>